name: Setup Bun
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun test
